packages:
  - packages/*
  - apps/*

dedupeDirectDeps: true

ignoredBuiltDependencies:
  - '@bufbuild/buf'

sharedWorkspaceLockfile: true

publicHoistPattern:
  - 'eslint' # So we can use the cli in all packages
