import type { StyleConfig } from '..'

export const poi_shop = (config: StyleConfig) => ({
  source: 'vector',
  id: 'poi-shop',
  type: 'symbol',
  'source-layer': 'pois',
  filter: ['to-boolean', ['get', 'shop']],
  minzoom: 16,
  layout: {
    'icon-size': {
      stops: [
        [16, 0.5],
        [19, 0.5],
        [20, 1],
      ],
    },
    'symbol-placement': 'point',
    'icon-optional': true,
    'text-font': ['Noto Sans Regular'],
    'text-field': [
      'coalesce',
      ['get', 'name_int'],
      ['get', 'name_en'],
      ['get', 'name:latin'],
      ['get', 'name'],
    ],
    'icon-anchor': 'bottom',
    'text-size': 10,
    'text-anchor': 'top',
    'icon-image': [
      'match',
      ['get', 'shop'],
      'alcohol',
      'mdi:liquor',
      'bakery',
      'mdi:cake',
      'beauty',
      'mdi:creation',
      'beverages',
      'mdi:beer',
      'books',
      'mdi:book-open-blank-variant',
      'butcher',
      'mdi:food-steak',
      'chemist',
      'mdi:flask-empty',
      'clothes',
      'mdi:tshirt-v',
      'doityourself',
      'mdi:tools',
      'dry_cleaning',
      'mdi:washing-machine',
      'florist',
      'mdi:flower',
      'furniture',
      'mdi:sofa',
      'garden_centre',
      'mdi:shovel',
      'general',
      'mdi:store',
      'gift',
      'mdi:gift',
      'greengrocer',
      'mdi:fruit-pear',
      'hairdresser',
      'mdi:content-cut',
      'hardware',
      'mdi:hammer-wrench',
      'jewelry',
      'mdi:necklace',
      'kiosk',
      'mdi:monitor-small',
      'laundry',
      'mdi:washing-machine',
      'newsagent',
      'mdi:newspaper-variant-multiple-outline',
      'optican',
      'mdi:glasses',
      'outdoor',
      'mdi:nature',
      'shoes',
      'mdi:shoe-heel',
      'sports',
      'mdi:tennis',
      'stationery',
      'mdi:pencil-ruler',
      'toys',
      'mdi:toy-brick',
      'travel_agency',
      'mdi:plane-train',
      'video',
      'mdi:movie-play',
      'mdi:store',
    ],
  },
  paint: {
    'icon-opacity': {
      stops: [
        [16, 0],
        [17, 0.4],
      ],
    },
    'text-opacity': {
      stops: [
        [16, 0],
        [17, 0.4],
      ],
    },
    'icon-color': 'rgb(85,85,85)',
    'text-color': 'rgb(85,85,85)',
  },
})
