import type { StyleConfig } from '..'

export const poi_amenity = (config: StyleConfig) => ({
  source: 'vector',
  id: 'poi-amenity',
  type: 'symbol',
  'source-layer': 'pois',
  filter: ['to-boolean', ['get', 'amenity']],
  minzoom: 16,
  layout: {
    'icon-size': {
      stops: [
        [16, 0.5],
        [19, 0.5],
        [20, 1],
      ],
    },
    'symbol-placement': 'point',
    'icon-optional': true,
    'text-font': ['Noto Sans Regular'],
    'text-field': [
      'coalesce',
      ['get', 'name_int'],
      ['get', 'name_en'],
      ['get', 'name:latin'],
      ['get', 'name'],
    ],
    'icon-anchor': 'bottom',
    'text-size': 10,
    'text-anchor': 'top',
    'icon-image': [
      'match',
      ['get', 'amenity'],
      'arts_centre',
      'mdi:view-gallery',
      'atm',
      'mdi:cash',
      'bank',
      'mdi:bank',
      'bar',
      'mdi:glass-cocktail',
      'bench',
      'mdi:bench',
      'bicycle_rental',
      'mdi:bike',
      'biergarten',
      'mdi:glass-mug-variant',
      'cafe',
      'mdi:coffee',
      'car_rental',
      'mdi:car-key',
      'car_sharing',
      'mdi:car-key',
      'car_wash',
      'mdi:car-wash',
      'cinema',
      'mdi:theater',
      'college',
      'mdi:book-education',
      'community_centre',
      'mdi:account-group',
      'dentist',
      'mdi:tooth',
      'doctors',
      'mdi:doctor',
      'dog_park',
      'mdi:dog-side',
      'drinking_water',
      'mdi:water',
      'embassy',
      'mdi:office-building',
      'fast_food',
      'mdi:food',
      'fire_station',
      'mdi:fire-station',
      'fountain',
      'mdi:fountain',
      'grave_yard',
      'mdi:grave-stone',
      'hospital',
      'mdi:hospital',
      'hunting_stand',
      'mdi:tower-fire',
      'library',
      'mdi:library',
      'marketplace',
      'mdi:shopping',
      'nightclub',
      'mdi:speaker',
      'nursing_home',
      'mdi:home-heart',
      'pharmacy',
      'mdi:pill',
      'place_of_worship',
      'mdi:church',
      'playground',
      'mdi:seesaw',
      'police',
      'mdi:police-badge',
      'post_box',
      'mdi:mailbox',
      'post_office',
      'mdi:email-variant',
      'prison',
      'mdi:handcuffs',
      'pub',
      'mdi:beer',
      'recycling',
      'mdi:recycle',
      'restaurant',
      'mdi:silverware',
      'school',
      'mdi:school',
      'shelter',
      'mdi:home-roof',
      'telephone',
      'mdi:phone',
      'theatre',
      'mdi:drama-masks',
      'toilets',
      'mdi:toilet',
      'townhall',
      'mdi:town-hall',
      'vending_machine',
      'mdi:candy',
      'veterinary',
      'mdi:dog-side',
      'waste_basket',
      'mdi:trash-can',
      '',
    ],
  },
  paint: {
    'icon-opacity': {
      stops: [
        [16, 0],
        [17, 0.4],
      ],
    },
    'text-opacity': {
      stops: [
        [16, 0],
        [17, 0.4],
      ],
    },
    'icon-color': 'rgb(85,85,85)',
    'text-color': 'rgb(85,85,85)',
  },
})
