import type { StyleConfig } from '..'

export const poi_amenity = (config: StyleConfig) => ({
  source: 'vector',
  id: 'poi-amenity',
  type: 'symbol',
  'source-layer': 'pois',
  filter: ['to-boolean', ['get', 'amenity']],
  minzoom: 16,
  layout: {
    'icon-size': {
      stops: [
        [16, 0.5],
        [19, 0.5],
        [20, 1],
      ],
    },
    'symbol-placement': 'point',
    'icon-optional': true,
    'text-font': ['Noto Sans Regular'],
    'icon-image': [
      'match',
      ['get', 'amenity'],
      'arts_centre',
      'basics:icon-art_gallery',
      'atm',
      'basics:icon-atm',
      'bank',
      'basics:icon-bank',
      'bar',
      'basics:icon-bar',
      'bench',
      'basics:icon-bench',
      'bicycle_rental',
      'basics:icon-bicycle_share',
      'biergarten',
      'basics:icon-beergarden',
      'cafe',
      'basics:icon-cafe',
      'car_rental',
      'basics:icon-car_rental',
      'car_sharing',
      'basics:icon-car_rental',
      'car_wash',
      'basics:icon-car_wash',
      'cinema',
      'basics:icon-cinema',
      'college',
      'basics:icon-college',
      'community_centre',
      'basics:icon-community',
      'dentist',
      'basics:icon-dentist',
      'doctors',
      'basics:icon-doctor',
      'dog_park',
      'basics:icon-dog_park',
      'drinking_water',
      'basics:icon-drinking_water',
      'embassy',
      'basics:icon-embassy',
      'fast_food',
      'basics:icon-fast_food',
      'fire_station',
      'basics:icon-fire_station',
      'fountain',
      'basics:icon-fountain',
      'grave_yard',
      'basics:icon-cemetery',
      'hospital',
      'basics:icon-hospital',
      'hunting_stand',
      'basics:icon-huntingstand',
      'library',
      'basics:icon-library',
      'marketplace',
      'basics:icon-marketplace',
      'nightclub',
      'basics:icon-nightclub',
      'nursing_home',
      'basics:icon-nursinghome',
      'pharmacy',
      'basics:icon-pharmacy',
      'place_of_worship',
      'basics:icon-place_of_worship',
      'playground',
      'basics:icon-playground',
      'police',
      'basics:icon-police',
      'post_box',
      'basics:icon-postbox',
      'post_office',
      'basics:icon-post',
      'prison',
      'basics:icon-prison',
      'pub',
      'basics:icon-beer',
      'recycling',
      'basics:icon-recycling',
      'restaurant',
      'basics:icon-restaurant',
      'school',
      'basics:icon-school',
      'shelter',
      'basics:icon-shelter',
      'telephone',
      'basics:icon-telephone',
      'theatre',
      'basics:icon-theatre',
      'toilets',
      'basics:icon-toilet',
      'townhall',
      'basics:icon-town_hall',
      'vending_machine',
      'basics:icon-vendingmachine',
      'veterinary',
      'basics:icon-veterinary',
      'waste_basket',
      'basics:icon-waste_basket',
      '',
    ],
  },
  paint: {
    'icon-opacity': {
      stops: [
        [16, 0],
        [17, 0.4],
      ],
    },
    'text-opacity': {
      stops: [
        [16, 0],
        [17, 0.4],
      ],
    },
    'icon-color': 'rgb(85,85,85)',
    'text-color': 'rgb(85,85,85)',
  },
})
