import type { StyleConfig } from '..'

export const poi_shop = (config: StyleConfig) => ({
  source: 'vector',
  id: 'poi-shop',
  type: 'symbol',
  'source-layer': 'pois',
  filter: ['to-boolean', ['get', 'shop']],
  minzoom: 16,
  layout: {
    'icon-size': {
      stops: [
        [16, 0.5],
        [19, 0.5],
        [20, 1],
      ],
    },
    'symbol-placement': 'point',
    'icon-optional': true,
    'text-font': ['Noto Sans Regular'],
    'text-field': [
      'coalesce',
      ['get', 'name_int'],
      ['get', 'name_en'],
      ['get', 'name:latin'],
      ['get', 'name'],
    ],
    'icon-anchor': 'bottom',
    'text-size': 10,
    'text-anchor': 'top',
    'icon-image': [
      'match',
      ['get', 'shop'],
      'alcohol',
      'basics:icon-alcohol_shop',
      'bakery',
      'basics:icon-bakery',
      'beauty',
      'basics:icon-beauty',
      'beverages',
      'basics:icon-beverages',
      'books',
      'basics:icon-books',
      'butcher',
      'basics:icon-butcher',
      'chemist',
      'basics:icon-chemist',
      'clothes',
      'basics:icon-clothes',
      'doityourself',
      'basics:icon-doityourself',
      'dry_cleaning',
      'basics:icon-drycleaning',
      'florist',
      'basics:icon-florist',
      'furniture',
      'basics:icon-furniture',
      'garden_centre',
      'basics:icon-garden_centre',
      'general',
      'basics:icon-shop',
      'gift',
      'basics:icon-gift',
      'greengrocer',
      'basics:icon-greengrocer',
      'hairdresser',
      'basics:icon-hairdresser',
      'hardware',
      'basics:icon-hardware',
      'jewelry',
      'basics:icon-jewelry_store',
      'kiosk',
      'basics:icon-kiosk',
      'laundry',
      'basics:icon-laundry',
      'newsagent',
      'basics:icon-newsagent',
      'optican',
      'basics:icon-optician',
      'outdoor',
      'basics:icon-outdoor',
      'shoes',
      'basics:icon-shoes',
      'sports',
      'basics:icon-sports',
      'stationery',
      'basics:icon-stationery',
      'toys',
      'basics:icon-toys',
      'travel_agency',
      'basics:icon-travel_agent',
      'video',
      'basics:icon-video',
      'basics:icon-shop',
    ],
  },
  paint: {
    'icon-opacity': {
      stops: [
        [16, 0],
        [17, 0.4],
      ],
    },
    'text-opacity': {
      stops: [
        [16, 0],
        [17, 0.4],
      ],
    },
    'icon-color': 'rgb(85,85,85)',
    'text-color': 'rgb(85,85,85)',
  },
})
