$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  format-check:
    command: pnpm
    args:
      - biome
      - check
    options:
      cache: false
      persistent: false

  format-fix:
    command: pnpm
    args:
      - biome
      - check
      - --fix
      - --unsafe
      - .
    options:
      cache: false
      persistent: false

  build:
    inputs:
      - src
    outputs:
      - dist
    command:
      - tsc
    options:
      cache: true
      persistent: false

  test:
    inputs:
      - src
    command: c8
    args:
      - --100
      - tsx
      - --test
      - src/**/*.spec.ts
    options:
      cache: true
      persistent: false

  lint:
    inputs:
      - src
    command: eslint
    args:
      - --cache
      - --cache-location
      - node_modules/.eslintcache
      - .
    options:
      cache: true
      persistent: false

  lint-fix:
    inputs:
      - src
    command: eslint
    args:
      - --cache
      - --cache-location
      - node_modules/.eslintcache
      - --fix
      - .
    options:
      cache: true
      persistent: false
