name: Vector tiles (single)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to the pbf'
        required: true
        default: 'https://download.geofabrik.de/europe/united-kingdom/england/greater-london-latest.osm.pbf'

      name:
        description: 'Name of the vector tiles'
        required: true
        default: 'greater-london'

      skip_free_disk_space:
        description: 'Skip free disk space step'
        required: false
        default: true
        type: boolean

      cloudflare_deploy:
        description: 'Deploy to Cloudflare'
        required: false
        default: true
        type: boolean

  workflow_call:
    inputs:
      skip_free_disk_space:
        default: false
        type: boolean

      cloudflare_deploy:
        default: false
        type: boolean

      url:
        required: true
        type: string

      name:
        required: true
        type: string

jobs:
  fail-if-not-pbf:
    if: "!contains(inputs.url, '.pbf')"

    runs-on: ubuntu-latest

    steps:
      - name: Fail if not .pbf
        run: |
          set -exu
          echo "Error: The URL must point to a .pbf file."
          exit 1

  build:
    runs-on: ubuntu-latest

    if: contains(inputs.url, '.pbf')

    steps:
      - name: Free Disk Space
        if: "!inputs.skip_free_disk_space"
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - uses: actions/checkout@v4

      - name: Get tooling from cache
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}

      - uses: asdf-vm/actions/install@v4

      - name: Get node_modules from cache
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
            apps/*/node_modules
          key: lock-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          set -exu
          pnpm install --frozen-lockfile

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '24'

      - name: Get planetiler from cache
        uses: actions/cache@v4
        id: cache-planetiler
        with:
          path: |
            /home/runner/planetiler.jar
            /home/runner/planetiler-cache
          key: planetiler-${{ inputs.name }}-${{ hashFiles('packages/map-tiles/bin/build_planetiles.sh') }}

      - name: Install Planetiler
        if: steps.cache-planetiler.outputs.cache-hit != 'true'
        run: |
          set -exu
          wget -q https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar -O /home/runner/planetiler.jar

      - name: Build
        working-directory: packages/map-tiles
        run: |
          set -exu
          bin/build_planetiles.sh "${{ inputs.url }}" dist/vector /home/runner/planetiler.jar /home/runner/planetiler-cache

      - uses: actions/upload-artifact@v4
        with:
          name: vector-tiles-${{ inputs.name }}
          path: packages/map-tiles/dist/vector/
          if-no-files-found: error
          retention-days: 7

      # - name: Upload Vector Tiles
      #   if: inputs.cloudflare_deploy == true
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_ACCOUNT_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      #     workingDirectory: packages/map-tiles
      #     command: |
      #       pages deploy dist/vector --project-name=project-maps-tiles --branch=${{ github.ref_name }}
