name: Vector tiles

on:
  workflow_dispatch:

jobs:
  tooling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: asdf-vm/actions/install@v3

      - name: Cache tooling
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}
          restore-keys: |
            tool-

  dependencies:
    needs:
      - tooling

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get tooling from cache
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}
          fail-on-cache-miss: true

      - uses: asdf-vm/actions/install@v3

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
            apps/*/node_modules
          key: lock-${{ hashFiles('pnpm.lock') }}
          restore-keys: |
            lock-

      - name: Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          set -exu
          pnpm install --frozen-lockfile

  build:
    strategy:
      fail-fast: true
      matrix:
        pbf:
          - name: europe_united-kingdom_england_cumbria
            url: http://download.geofabrik.de/europe/united-kingdom/england/cumbria-latest.osm.pbf

          - name: europe_united-kingdom_england_derbyshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/derbyshire-latest.osm.pbf

          - name: europe_united-kingdom_england_devon
            url: http://download.geofabrik.de/europe/united-kingdom/england/devon-latest.osm.pbf

          - name: europe_united-kingdom_england_dorset
            url: http://download.geofabrik.de/europe/united-kingdom/england/dorset-latest.osm.pbf

          - name: europe_united-kingdom_england_durham
            url: http://download.geofabrik.de/europe/united-kingdom/england/durham-latest.osm.pbf

          - name: europe_united-kingdom_england_east-sussex
            url: http://download.geofabrik.de/europe/united-kingdom/england/east-sussex-latest.osm.pbf

          - name: europe_united-kingdom_england_east-yorkshire-with-hull
            url: http://download.geofabrik.de/europe/united-kingdom/england/east-yorkshire-with-hull-latest.osm.pbf

          - name: europe_united-kingdom_england_essex
            url: http://download.geofabrik.de/europe/united-kingdom/england/essex-latest.osm.pbf

          - name: europe_united-kingdom_england_gloucestershire
            url: http://download.geofabrik.de/europe/united-kingdom/england/gloucestershire-latest.osm.pbf

          - name: europe_united-kingdom_england_greater-london
            url: http://download.geofabrik.de/europe/united-kingdom/england/greater-london-latest.osm.pbf

          - name: europe_united-kingdom_england_greater-manchester
            url: http://download.geofabrik.de/europe/united-kingdom/england/greater-manchester-latest.osm.pbf

          - name: europe_united-kingdom_england_hampshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/hampshire-latest.osm.pbf

          - name: europe_united-kingdom_england_herefordshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/herefordshire-latest.osm.pbf

          - name: europe_united-kingdom_england_hertfordshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/hertfordshire-latest.osm.pbf

          - name: europe_united-kingdom_england_isle-of-wight
            url: http://download.geofabrik.de/europe/united-kingdom/england/isle-of-wight-latest.osm.pbf

          - name: europe_united-kingdom_england_kent
            url: http://download.geofabrik.de/europe/united-kingdom/england/kent-latest.osm.pbf

          - name: europe_united-kingdom_england_lancashire
            url: http://download.geofabrik.de/europe/united-kingdom/england/lancashire-latest.osm.pbf

          - name: europe_united-kingdom_england_leicestershire
            url: http://download.geofabrik.de/europe/united-kingdom/england/leicestershire-latest.osm.pbf

          - name: europe_united-kingdom_england_lincolnshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/lincolnshire-latest.osm.pbf

          - name: europe_united-kingdom_england_merseyside
            url: http://download.geofabrik.de/europe/united-kingdom/england/merseyside-latest.osm.pbf

          - name: europe_united-kingdom_england_norfolk
            url: http://download.geofabrik.de/europe/united-kingdom/england/norfolk-latest.osm.pbf

          - name: europe_united-kingdom_england_north-yorkshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/north-yorkshire-latest.osm.pbf

          - name: europe_united-kingdom_england_northamptonshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/northamptonshire-latest.osm.pbf

          - name: europe_united-kingdom_england_northumberland
            url: http://download.geofabrik.de/europe/united-kingdom/england/northumberland-latest.osm.pbf

          - name: europe_united-kingdom_england_nottinghamshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/nottinghamshire-latest.osm.pbf

          - name: europe_united-kingdom_england_oxfordshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/oxfordshire-latest.osm.pbf

          - name: europe_united-kingdom_england_rutland
            url: http://download.geofabrik.de/europe/united-kingdom/england/rutland-latest.osm.pbf

          - name: europe_united-kingdom_england_shropshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/shropshire-latest.osm.pbf

          - name: europe_united-kingdom_england_somerset
            url: http://download.geofabrik.de/europe/united-kingdom/england/somerset-latest.osm.pbf

          - name: europe_united-kingdom_england_south-yorkshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/south-yorkshire-latest.osm.pbf

          - name: europe_united-kingdom_england_staffordshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/staffordshire-latest.osm.pbf

          - name: europe_united-kingdom_england_suffolk
            url: http://download.geofabrik.de/europe/united-kingdom/england/suffolk-latest.osm.pbf

          - name: europe_united-kingdom_england_surrey
            url: http://download.geofabrik.de/europe/united-kingdom/england/surrey-latest.osm.pbf

          - name: europe_united-kingdom_england_tyne-and-wear
            url: http://download.geofabrik.de/europe/united-kingdom/england/tyne-and-wear-latest.osm.pbf

          - name: europe_united-kingdom_england_warwickshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/warwickshire-latest.osm.pbf

          - name: europe_united-kingdom_england_west-midlands
            url: http://download.geofabrik.de/europe/united-kingdom/england/west-midlands-latest.osm.pbf

          - name: europe_united-kingdom_england_west-sussex
            url: http://download.geofabrik.de/europe/united-kingdom/england/west-sussex-latest.osm.pbf

          - name: europe_united-kingdom_england_west-yorkshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/west-yorkshire-latest.osm.pbf

          - name: europe_united-kingdom_england_wiltshire
            url: http://download.geofabrik.de/europe/united-kingdom/england/wiltshire-latest.osm.pbf

          - name: europe_united-kingdom_england_worcestershire
            url: http://download.geofabrik.de/europe/united-kingdom/england/worcestershire-latest.osm.pbf

    needs:
      - dependencies

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get tooling from cache
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}
          fail-on-cache-miss: true

      - uses: asdf-vm/actions/install@v3

      - name: Get node_modules from cache
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
            apps/*/node_modules
          key: lock-${{ hashFiles('pnpm.lock') }}
          fail-on-cache-miss: true

      - name: Configure build
        run: |
          printf '{"pbfs":["${{ matrix.pbf.url }}"]}\n' > packages/map-tiles/build-input.json

      - name: Build
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: |
          set -exu
          pnpm moon map-tiles:build_vector

      - name: Upload vector tiles
        uses: actions/upload-artifact@v4
        with:
          name: vector-tiles-${{ matrix.pbf.name }}
          path: packages/map-tiles/dist/vector
