name: Vector tiles

on:
  workflow_dispatch:

jobs:
  tooling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache tooling
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}

      - uses: asdf-vm/actions/install@v4
        if: steps.cache-tooling.outputs.cache-hit != 'true'

      - name: Cache planetiler
        uses: actions/cache@v4
        id: cache-planetiler
        with:
          path: |
            /home/runner/planetiler.jar
          key: planetiler

      - name: Install Planetiler
        if: steps.cache-planetiler.outputs.cache-hit != 'true'
        run: |
          set -exu
          wget -q https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar -O /home/runner/planetiler.jar

  dependencies:
    needs:
      - tooling

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get tooling from cache
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}
          fail-on-cache-miss: true

      - uses: asdf-vm/actions/install@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
            apps/*/node_modules
          key: lock-${{ hashFiles('pnpm-lock.yaml') }}c
          lookup-only: true

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          set -exu
          pnpm install --frozen-lockfile

  depth-0-plan:
    needs:
      - dependencies

    uses: ./.github/workflows/create-recursion-matrix.yml
    with:
      url: https://download.geofabrik.de/

  depth-0:
    needs:
      - dependencies
      - depth-0-plan

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        pbf: ${{ fromJson(needs.depth-0-plan.outputs.matrix) }}
        ocean_url:
          - https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip
        admin_points_url:
          - https://shortbread.geofabrik.de/shapefiles/admin-points-4326.zip

    uses: ./.github/workflows/vector-tiles-depth-1.yml
    with:
      url: ${{ matrix.pbf.url }}
      name: ${{ matrix.pbf.name }}
      ocean_url: ${{ matrix.ocean_url }}
      admin_points_url: ${{ matrix.admin_points_url }}

  merge:
    needs:
      - depth-0

    uses: ./.github/workflows/vector-tiles-merge.yml
