name: Vector tiles (single)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to the pbf'
        required: true
        default: 'https://download.geofabrik.de/europe/united-kingdom/england/greater-london-latest.osm.pbf'

      name:
        description: 'Name of the vector tiles'
        required: true
        default: 'greater-london'

      ocean_url:
        description: 'URL to the ocean polygons'
        required: true
        default: 'https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip'

      admin_points_url:
        description: 'URL to the admin points shapefile'
        required: true
        default: 'https://shortbread.geofabrik.de/shapefiles/admin-points-4326.zip'

      skip_free_disk_space:
        description: 'Skip free disk space step'
        required: false
        default: true
        type: boolean

  workflow_call:
    inputs:
      skip_free_disk_space:
        default: false
        type: boolean

      url:
        required: true
        type: string

      ocean_url:
        required: true
        type: string

      admin_points_url:
        required: true
        type: string

      name:
        required: true
        type: string

jobs:
  fail-if-not-pbf:
    if: "!contains(inputs.url, '.pbf')"

    runs-on: ubuntu-latest

    steps:
      - name: Fail if not .pbf
        run: |
          set -exu
          echo "Error: The URL must point to a .pbf file."
          exit 1

  build:
    runs-on: ubuntu-latest

    if: contains(inputs.url, '.pbf')

    steps:
      - name: Maximise Disk Space
        if: "!inputs.skip_free_disk_space"
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 10240
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '24'

      - name: Get planetiler from cache
        uses: actions/cache@v4
        id: cache-planetiler
        with:
          path: |
            /home/runner/planetiler.jar
          key: planetiler

      - name: Install Planetiler
        if: steps.cache-planetiler.outputs.cache-hit != 'true'
        run: |
          set -exu
          wget -q https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar -O /home/runner/planetiler.jar

      - name: Get planetiler data cache
        uses: actions/cache@v4
        id: cache-planetiler-data
        with:
          path: |
            /home/runner/work/project-maps/project-maps/planetiler-cache
          key: planetiler-data-${{ github.run_id }}

      - name: Build
        working-directory: packages/map-tiles
        run: |
          set -exu
          bin/build_planetiles.sh "${{ inputs.url }}" "${{ inputs.ocean_url }}" "${{ inputs.admin_points_url }}" dist/vector /home/runner/work/project-maps/project-maps/planetiler-cache

      - name: Zip Vector Tiles
        working-directory: packages/map-tiles
        run: |
          set -exu
          zip -rqmy0 dist/vector.zip dist/vector

      - uses: actions/upload-artifact@v4
        with:
          name: vector-tiles-${{ inputs.name }}
          path: packages/map-tiles/dist/vector.zip
          if-no-files-found: error
          retention-days: 7
          overwrite: 'true'
