name: Vector tiles (depth 3)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

      url:
        required: true
        type: string

jobs:
  fail-if-not-pbf:
    runs-on: ubuntu-latest

    if: contains(inputs.url, '.html')

    steps:
      - name: Fail if not .osm.pbf
        run: |
          set -exu
          echo "Ran out of depth."
          exit 1

  build:
    if: contains(inputs.url, '.osm.pbf')

    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        if: "!inputs.skip_free_disk_space"
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - uses: actions/checkout@v4

      - name: Get tooling from cache
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}

      - uses: asdf-vm/actions/install@v4

      - name: Get node_modules from cache
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
            apps/*/node_modules
          key: lock-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          set -exu
          pnpm install --frozen-lockfile

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '24'

      - name: Get planetiler from cache
        uses: actions/cache@v4
        id: cache-planetiler
        with:
          path: |
            /home/runner/planetiler.jar
            /home/runner/planetiler-cache
          key: planetiler-${{ inputs.name }}-${{ hashFiles('packages/map-tiles/bin/build_planetiles.sh') }}

      - name: Install Planetiler
        if: steps.cache-planetiler.outputs.cache-hit != 'true'
        run: |
          set -exu
          wget -q https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar -O /home/runner/planetiler.jar

      - name: Build
        working-directory: packages/map-tiles
        run: |
          set -exu
          bin/build_planetiles.sh "${{ inputs.url }}" dist/vector /home/runner/planetiler.jar /home/runner/planetiler-cache
