name: Vector tiles (depth 2)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

      url:
        required: true
        type: string

      ocean_url:
        required: true
        type: string

      admin_points_url:
        required: true
        type: string

jobs:
  create-recursion-matrix:
    if: contains(inputs.url, '.html')

    uses: ./.github/workflows/create-recursion-matrix.yml
    with:
      url: ${{ inputs.url }}

  recurse:
    needs:
      - create-recursion-matrix

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        pbf: ${{ fromJson(needs.create-recursion-matrix.outputs.matrix) }}

    uses: ./.github/workflows/vector-tiles-depth-3.yml
    with:
      url: ${{ matrix.pbf.url }}
      name: ${{ matrix.pbf.name }}
      ocean_url: ${{ inputs.ocean_url }}
      admin_points_url: ${{ inputs.admin_points_url }}

  build:
    if: contains(inputs.url, '.osm.pbf')

    uses: ./.github/workflows/vector-tiles-single.yml
    with:
      url: ${{ inputs.url }}
      name: ${{ inputs.name }}
      ocean_url: ${{ inputs.ocean_url }}
      admin_points_url: ${{ inputs.admin_points_url }}
