name: Vector tiles (depth 3)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

      url:
        required: true
        type: string

      ocean_url:
        required: true
        type: string

      admin_points_url:
        required: true
        type: string

jobs:
  fail-if-not-pbf:
    runs-on: ubuntu-latest

    if: contains(inputs.url, '.html')

    steps:
      - name: Fail if not .osm.pbf
        run: |
          set -exu
          echo "Ran out of depth."
          exit 1

  build:
    if: contains(inputs.url, '.osm.pbf')

    runs-on: ubuntu-latest

    steps:
      - name: Maximise Disk Space
        if: "!inputs.skip_free_disk_space"
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 10240
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '24'

      - name: Get planetiler from cache
        uses: actions/cache@v4
        id: cache-planetiler
        with:
          path: |
            /home/runner/planetiler.jar
          key: planetiler
          fail-on-cache-miss: true

      - name: Get planetiler data cache
        uses: actions/cache@v4
        id: cache-planetiler-data
        with:
          path: |
            /home/runner/planetiler-cache
          key: planetiler-${{ hashFiles('packages/map-tiles/bin/build_planetiles.sh') }}

      - name: Build
        working-directory: packages/map-tiles
        run: |
          set -exu
          bin/build_planetiles.sh "${{ inputs.url }}" "${{ inputs.ocean_url }}" "${{ inputs.admin_points_url }}" dist/vector /home/runner/planetiler.jar /home/runner/planetiler-cache

      - name: Zip Vector Tiles
        working-directory: packages/map-tiles
        run: |
          set -exu
          zip -rqmy0 dist/vector.zip dist/vector

      - uses: actions/upload-artifact@v4
        with:
          name: vector-tiles-${{ inputs.name }}
          path: packages/map-tiles/dist/vector.zip
          if-no-files-found: error
          retention-days: 7
          overwrite: 'true'
