name: Vector tiles (single)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to the pbf'
        required: true
        default: 'https://download.geofabrik.de/europe/united-kingdom/england/greater-london-latest.osm.pbf'

      skip_free_disk_space:
        description: 'Skip free disk space step'
        required: false
        default: true
        type: boolean

  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  fail-if-not-pbf:
    if: "!contains(inputs.url, '.pbf')"

    runs-on: ubuntu-latest

    steps:
      - name: Fail if not .pbf
        run: |
          set -exu
          echo "Error: The URL must point to a .pbf file."
          exit 1

  build:
    runs-on: ubuntu-latest

    if: contains(inputs.url, '.pbf')

    steps:
      - name: Free Disk Space
        if: "!inputs.skip_free_disk_space"
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - uses: actions/checkout@v4

      - name: Cache tooling
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}

      - uses: asdf-vm/actions/install@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
            apps/*/node_modules
          key: lock-${{ hashFiles('pnpm-lock.yaml') }}c
          lookup-only: true

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          set -exu
          pnpm install --frozen-lockfile

      - name: Cache planetiler
        uses: actions/cache@v4
        id: cache-planetiler
        with:
          path: |
            /home/runner/planetiler.jar
          key: planetiler

      - name: Install Planetiler
        if: steps.cache-planetiler.outputs.cache-hit != 'true'
        run: |
          set -exu
          wget https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar -O /home/runner/planetiler.jar

      - name: Build
        working-directory: packages/map-tiles
        run: |
          set -exu
          bin/build_planetiles.sh "${{ inputs.url }}" dist/vector /home/runner/planetiler.jar
