name: Vector tiles (depth 2)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

      url:
        required: true
        type: string

jobs:
  create-recursion-matrix:
    runs-on: ubuntu-latest

    if: contains(inputs.url, '.html')

    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Get tooling from cache
        uses: actions/cache@v4
        id: cache-tooling
        with:
          path: |
            /home/runner/.asdf
          key: tool-${{ hashFiles('.tool-versions') }}
          fail-on-cache-miss: true

      - uses: asdf-vm/actions/install@v4

      - name: Get node_modules from cache
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
            apps/*/node_modules
          key: lock-${{ hashFiles('pnpm-lock.yaml') }}
          fail-on-cache-miss: true

      - name: Create matrix
        id: create-matrix
        working-directory: packages/map-tiles
        run: |
          set -exu
          echo "matrix=$(pnpm tsx bin/get-geofabrik-matrix.ts ${{ inputs.url }})" >> $GITHUB_OUTPUT

  recurse:
    needs:
      - create-recursion-matrix

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        pbf: ${{ fromJson(needs.create-recursion-matrix.outputs.matrix) }}

    uses: ./.github/workflows/vector-tiles-depth-3.yml
    with:
      url: ${{ matrix.pbf.url }}
      name: ${{ matrix.pbf.name }}

  build:
    if: contains(inputs.url, '.osm.pbf')

    uses: ./.github/workflows/vector-tiles-single.yml
    with:
      url: ${{ inputs.url }}
      name: ${{ inputs.name }}
