name: Vector tiles (depth 2)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

      url:
        required: true
        type: string

      ocean_url:
        required: true
        type: string

      admin_points_url:
        required: true
        type: string

jobs:
  depth-2-plan:
    if: contains(inputs.url, '.html')

    uses: ./.github/workflows/create-recursion-matrix.yml
    with:
      url: ${{ inputs.url }}
      current_depth: 2
      max_depth: 2

  depth-2:
    needs:
      - depth-2-plan

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        pbf: ${{ fromJson(needs.depth-2-plan.outputs.matrix) }}

    uses: ./.github/workflows/vector-tiles-depth-3.yml
    with:
      url: ${{ matrix.pbf.url }}
      name: ${{ matrix.pbf.name }}
      ocean_url: ${{ inputs.ocean_url }}
      admin_points_url: ${{ inputs.admin_points_url }}

  rerun-on-failure:
    runs-on: ubuntu-latest

    needs:
      - depth-2

    if: failure() && fromJSON(github.run_attempt) < 3

    steps:
      - run: gh workflow run rerun.yml -r ${{ github.head_ref || github.ref_name }} -F run_id=${{ github.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api

  build:
    if: contains(inputs.url, '.osm.pbf')

    uses: ./.github/workflows/vector-tiles-single.yml
    with:
      url: ${{ inputs.url }}
      name: ${{ inputs.name }}
      ocean_url: ${{ inputs.ocean_url }}
      admin_points_url: ${{ inputs.admin_points_url }}
