name: Vector tiles (depth 3)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

      url:
        required: true
        type: string

jobs:
  fail-if-not-pbf:
    runs-on: ubuntu-latest

    if: contains(inputs.url, '.html')

    steps:
      - name: Fail if not .osm.pbf
        run: |
          set -exu
          echo "Ran out of depth."
          exit 1

  build:
    if: contains(inputs.url, '.osm.pbf')

    uses: ./.github/workflows/vector-tiles-single.yml
    with:
      url: ${{ inputs.url }}
      name: ${{ inputs.name }}
